server:
  port: 8083

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5433/notification
    username: postgres
    password: Xk7mN9vpQL2nRw4j
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      registered: account.registered
      logged-in: account.logged-in
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
