apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-init-config
  namespace: kafka
data:
  kafka-init.properties: |
    node.id=1
    process.roles=broker,controller
    controller.quorum.voters=1@kafka-0.kafka-headless.kafka.svc.cluster.local:9093
    listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
    listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    controller.listener.names=CONTROLLER
    inter.broker.listener.name=PLAINTEXT
    log.dirs=/var/lib/kafka/data
