/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.seanglay.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AccountRegisteredEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1947065067775306578L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AccountRegisteredEvent\",\"namespace\":\"com.seanglay.events\",\"fields\":[{\"name\":\"account_id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"registered_at\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<AccountRegisteredEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AccountRegisteredEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AccountRegisteredEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AccountRegisteredEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AccountRegisteredEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AccountRegisteredEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AccountRegisteredEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AccountRegisteredEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AccountRegisteredEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence account_id;
  private java.lang.CharSequence name;
  private java.lang.CharSequence email;
  private java.time.Instant registered_at;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AccountRegisteredEvent() {}

  /**
   * All-args constructor.
   * @param account_id The new value for account_id
   * @param name The new value for name
   * @param email The new value for email
   * @param registered_at The new value for registered_at
   */
  public AccountRegisteredEvent(java.lang.CharSequence account_id, java.lang.CharSequence name, java.lang.CharSequence email, java.time.Instant registered_at) {
    this.account_id = account_id;
    this.name = name;
    this.email = email;
    this.registered_at = registered_at.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return account_id;
    case 1: return name;
    case 2: return email;
    case 3: return registered_at;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: account_id = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: email = (java.lang.CharSequence)value$; break;
    case 3: registered_at = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'account_id' field.
   * @return The value of the 'account_id' field.
   */
  public java.lang.CharSequence getAccountId() {
    return account_id;
  }


  /**
   * Sets the value of the 'account_id' field.
   * @param value the value to set.
   */
  public void setAccountId(java.lang.CharSequence value) {
    this.account_id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }


  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'registered_at' field.
   * @return The value of the 'registered_at' field.
   */
  public java.time.Instant getRegisteredAt() {
    return registered_at;
  }


  /**
   * Sets the value of the 'registered_at' field.
   * @param value the value to set.
   */
  public void setRegisteredAt(java.time.Instant value) {
    this.registered_at = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new AccountRegisteredEvent RecordBuilder.
   * @return A new AccountRegisteredEvent RecordBuilder
   */
  public static com.seanglay.events.AccountRegisteredEvent.Builder newBuilder() {
    return new com.seanglay.events.AccountRegisteredEvent.Builder();
  }

  /**
   * Creates a new AccountRegisteredEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AccountRegisteredEvent RecordBuilder
   */
  public static com.seanglay.events.AccountRegisteredEvent.Builder newBuilder(com.seanglay.events.AccountRegisteredEvent.Builder other) {
    if (other == null) {
      return new com.seanglay.events.AccountRegisteredEvent.Builder();
    } else {
      return new com.seanglay.events.AccountRegisteredEvent.Builder(other);
    }
  }

  /**
   * Creates a new AccountRegisteredEvent RecordBuilder by copying an existing AccountRegisteredEvent instance.
   * @param other The existing instance to copy.
   * @return A new AccountRegisteredEvent RecordBuilder
   */
  public static com.seanglay.events.AccountRegisteredEvent.Builder newBuilder(com.seanglay.events.AccountRegisteredEvent other) {
    if (other == null) {
      return new com.seanglay.events.AccountRegisteredEvent.Builder();
    } else {
      return new com.seanglay.events.AccountRegisteredEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for AccountRegisteredEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AccountRegisteredEvent>
    implements org.apache.avro.data.RecordBuilder<AccountRegisteredEvent> {

    private java.lang.CharSequence account_id;
    private java.lang.CharSequence name;
    private java.lang.CharSequence email;
    private java.time.Instant registered_at;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.seanglay.events.AccountRegisteredEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.account_id)) {
        this.account_id = data().deepCopy(fields()[0].schema(), other.account_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.email)) {
        this.email = data().deepCopy(fields()[2].schema(), other.email);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.registered_at)) {
        this.registered_at = data().deepCopy(fields()[3].schema(), other.registered_at);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing AccountRegisteredEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.seanglay.events.AccountRegisteredEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.account_id)) {
        this.account_id = data().deepCopy(fields()[0].schema(), other.account_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.email)) {
        this.email = data().deepCopy(fields()[2].schema(), other.email);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.registered_at)) {
        this.registered_at = data().deepCopy(fields()[3].schema(), other.registered_at);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'account_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getAccountId() {
      return account_id;
    }


    /**
      * Sets the value of the 'account_id' field.
      * @param value The value of 'account_id'.
      * @return This builder.
      */
    public com.seanglay.events.AccountRegisteredEvent.Builder setAccountId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.account_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'account_id' field has been set.
      * @return True if the 'account_id' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'account_id' field.
      * @return This builder.
      */
    public com.seanglay.events.AccountRegisteredEvent.Builder clearAccountId() {
      account_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.seanglay.events.AccountRegisteredEvent.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.seanglay.events.AccountRegisteredEvent.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }


    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.seanglay.events.AccountRegisteredEvent.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.email = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.seanglay.events.AccountRegisteredEvent.Builder clearEmail() {
      email = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'registered_at' field.
      * @return The value.
      */
    public java.time.Instant getRegisteredAt() {
      return registered_at;
    }


    /**
      * Sets the value of the 'registered_at' field.
      * @param value The value of 'registered_at'.
      * @return This builder.
      */
    public com.seanglay.events.AccountRegisteredEvent.Builder setRegisteredAt(java.time.Instant value) {
      validate(fields()[3], value);
      this.registered_at = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'registered_at' field has been set.
      * @return True if the 'registered_at' field has been set, false otherwise.
      */
    public boolean hasRegisteredAt() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'registered_at' field.
      * @return This builder.
      */
    public com.seanglay.events.AccountRegisteredEvent.Builder clearRegisteredAt() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AccountRegisteredEvent build() {
      try {
        AccountRegisteredEvent record = new AccountRegisteredEvent();
        record.account_id = fieldSetFlags()[0] ? this.account_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.email = fieldSetFlags()[2] ? this.email : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.registered_at = fieldSetFlags()[3] ? this.registered_at : (java.time.Instant) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AccountRegisteredEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<AccountRegisteredEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AccountRegisteredEvent>
    READER$ = (org.apache.avro.io.DatumReader<AccountRegisteredEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










