/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.seanglay.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TransactionCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3644771639487234548L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransactionCreatedEvent\",\"namespace\":\"com.seanglay.events\",\"fields\":[{\"name\":\"transaction_id\",\"type\":\"string\"},{\"name\":\"account_id\",\"type\":\"string\"},{\"name\":\"wallet_id\",\"type\":\"string\"},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"TransactionType\",\"symbols\":[\"DEPOSIT\",\"WITHDRAW\",\"TRANSFER_IN\",\"TRANSFER_OUT\"]}},{\"name\":\"amount\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":19,\"scale\":2}},{\"name\":\"related_wallet_id\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"created_at\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<TransactionCreatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransactionCreatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TransactionCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TransactionCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TransactionCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TransactionCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TransactionCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TransactionCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TransactionCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence transaction_id;
  private java.lang.CharSequence account_id;
  private java.lang.CharSequence wallet_id;
  private com.seanglay.events.TransactionType type;
  private java.nio.ByteBuffer amount;
  private java.lang.CharSequence related_wallet_id;
  private java.time.Instant created_at;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransactionCreatedEvent() {}

  /**
   * All-args constructor.
   * @param transaction_id The new value for transaction_id
   * @param account_id The new value for account_id
   * @param wallet_id The new value for wallet_id
   * @param type The new value for type
   * @param amount The new value for amount
   * @param related_wallet_id The new value for related_wallet_id
   * @param created_at The new value for created_at
   */
  public TransactionCreatedEvent(java.lang.CharSequence transaction_id, java.lang.CharSequence account_id, java.lang.CharSequence wallet_id, com.seanglay.events.TransactionType type, java.nio.ByteBuffer amount, java.lang.CharSequence related_wallet_id, java.time.Instant created_at) {
    this.transaction_id = transaction_id;
    this.account_id = account_id;
    this.wallet_id = wallet_id;
    this.type = type;
    this.amount = amount;
    this.related_wallet_id = related_wallet_id;
    this.created_at = created_at.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return transaction_id;
    case 1: return account_id;
    case 2: return wallet_id;
    case 3: return type;
    case 4: return amount;
    case 5: return related_wallet_id;
    case 6: return created_at;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: transaction_id = (java.lang.CharSequence)value$; break;
    case 1: account_id = (java.lang.CharSequence)value$; break;
    case 2: wallet_id = (java.lang.CharSequence)value$; break;
    case 3: type = (com.seanglay.events.TransactionType)value$; break;
    case 4: amount = (java.nio.ByteBuffer)value$; break;
    case 5: related_wallet_id = (java.lang.CharSequence)value$; break;
    case 6: created_at = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'transaction_id' field.
   * @return The value of the 'transaction_id' field.
   */
  public java.lang.CharSequence getTransactionId() {
    return transaction_id;
  }


  /**
   * Sets the value of the 'transaction_id' field.
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.CharSequence value) {
    this.transaction_id = value;
  }

  /**
   * Gets the value of the 'account_id' field.
   * @return The value of the 'account_id' field.
   */
  public java.lang.CharSequence getAccountId() {
    return account_id;
  }


  /**
   * Sets the value of the 'account_id' field.
   * @param value the value to set.
   */
  public void setAccountId(java.lang.CharSequence value) {
    this.account_id = value;
  }

  /**
   * Gets the value of the 'wallet_id' field.
   * @return The value of the 'wallet_id' field.
   */
  public java.lang.CharSequence getWalletId() {
    return wallet_id;
  }


  /**
   * Sets the value of the 'wallet_id' field.
   * @param value the value to set.
   */
  public void setWalletId(java.lang.CharSequence value) {
    this.wallet_id = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public com.seanglay.events.TransactionType getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(com.seanglay.events.TransactionType value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public java.nio.ByteBuffer getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(java.nio.ByteBuffer value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'related_wallet_id' field.
   * @return The value of the 'related_wallet_id' field.
   */
  public java.lang.CharSequence getRelatedWalletId() {
    return related_wallet_id;
  }


  /**
   * Sets the value of the 'related_wallet_id' field.
   * @param value the value to set.
   */
  public void setRelatedWalletId(java.lang.CharSequence value) {
    this.related_wallet_id = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public java.time.Instant getCreatedAt() {
    return created_at;
  }


  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.created_at = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new TransactionCreatedEvent RecordBuilder.
   * @return A new TransactionCreatedEvent RecordBuilder
   */
  public static com.seanglay.events.TransactionCreatedEvent.Builder newBuilder() {
    return new com.seanglay.events.TransactionCreatedEvent.Builder();
  }

  /**
   * Creates a new TransactionCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransactionCreatedEvent RecordBuilder
   */
  public static com.seanglay.events.TransactionCreatedEvent.Builder newBuilder(com.seanglay.events.TransactionCreatedEvent.Builder other) {
    if (other == null) {
      return new com.seanglay.events.TransactionCreatedEvent.Builder();
    } else {
      return new com.seanglay.events.TransactionCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new TransactionCreatedEvent RecordBuilder by copying an existing TransactionCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new TransactionCreatedEvent RecordBuilder
   */
  public static com.seanglay.events.TransactionCreatedEvent.Builder newBuilder(com.seanglay.events.TransactionCreatedEvent other) {
    if (other == null) {
      return new com.seanglay.events.TransactionCreatedEvent.Builder();
    } else {
      return new com.seanglay.events.TransactionCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for TransactionCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransactionCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<TransactionCreatedEvent> {

    private java.lang.CharSequence transaction_id;
    private java.lang.CharSequence account_id;
    private java.lang.CharSequence wallet_id;
    private com.seanglay.events.TransactionType type;
    private java.nio.ByteBuffer amount;
    private java.lang.CharSequence related_wallet_id;
    private java.time.Instant created_at;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.seanglay.events.TransactionCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[0].schema(), other.transaction_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.account_id)) {
        this.account_id = data().deepCopy(fields()[1].schema(), other.account_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.wallet_id)) {
        this.wallet_id = data().deepCopy(fields()[2].schema(), other.wallet_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.type)) {
        this.type = data().deepCopy(fields()[3].schema(), other.type);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.amount)) {
        this.amount = data().deepCopy(fields()[4].schema(), other.amount);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.related_wallet_id)) {
        this.related_wallet_id = data().deepCopy(fields()[5].schema(), other.related_wallet_id);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.created_at)) {
        this.created_at = data().deepCopy(fields()[6].schema(), other.created_at);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing TransactionCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.seanglay.events.TransactionCreatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.transaction_id)) {
        this.transaction_id = data().deepCopy(fields()[0].schema(), other.transaction_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.account_id)) {
        this.account_id = data().deepCopy(fields()[1].schema(), other.account_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.wallet_id)) {
        this.wallet_id = data().deepCopy(fields()[2].schema(), other.wallet_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.type)) {
        this.type = data().deepCopy(fields()[3].schema(), other.type);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.amount)) {
        this.amount = data().deepCopy(fields()[4].schema(), other.amount);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.related_wallet_id)) {
        this.related_wallet_id = data().deepCopy(fields()[5].schema(), other.related_wallet_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.created_at)) {
        this.created_at = data().deepCopy(fields()[6].schema(), other.created_at);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'transaction_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getTransactionId() {
      return transaction_id;
    }


    /**
      * Sets the value of the 'transaction_id' field.
      * @param value The value of 'transaction_id'.
      * @return This builder.
      */
    public com.seanglay.events.TransactionCreatedEvent.Builder setTransactionId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.transaction_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'transaction_id' field has been set.
      * @return True if the 'transaction_id' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'transaction_id' field.
      * @return This builder.
      */
    public com.seanglay.events.TransactionCreatedEvent.Builder clearTransactionId() {
      transaction_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'account_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getAccountId() {
      return account_id;
    }


    /**
      * Sets the value of the 'account_id' field.
      * @param value The value of 'account_id'.
      * @return This builder.
      */
    public com.seanglay.events.TransactionCreatedEvent.Builder setAccountId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.account_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'account_id' field has been set.
      * @return True if the 'account_id' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'account_id' field.
      * @return This builder.
      */
    public com.seanglay.events.TransactionCreatedEvent.Builder clearAccountId() {
      account_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'wallet_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getWalletId() {
      return wallet_id;
    }


    /**
      * Sets the value of the 'wallet_id' field.
      * @param value The value of 'wallet_id'.
      * @return This builder.
      */
    public com.seanglay.events.TransactionCreatedEvent.Builder setWalletId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.wallet_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'wallet_id' field has been set.
      * @return True if the 'wallet_id' field has been set, false otherwise.
      */
    public boolean hasWalletId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'wallet_id' field.
      * @return This builder.
      */
    public com.seanglay.events.TransactionCreatedEvent.Builder clearWalletId() {
      wallet_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public com.seanglay.events.TransactionType getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.seanglay.events.TransactionCreatedEvent.Builder setType(com.seanglay.events.TransactionType value) {
      validate(fields()[3], value);
      this.type = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.seanglay.events.TransactionCreatedEvent.Builder clearType() {
      type = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.seanglay.events.TransactionCreatedEvent.Builder setAmount(java.nio.ByteBuffer value) {
      validate(fields()[4], value);
      this.amount = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.seanglay.events.TransactionCreatedEvent.Builder clearAmount() {
      amount = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'related_wallet_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getRelatedWalletId() {
      return related_wallet_id;
    }


    /**
      * Sets the value of the 'related_wallet_id' field.
      * @param value The value of 'related_wallet_id'.
      * @return This builder.
      */
    public com.seanglay.events.TransactionCreatedEvent.Builder setRelatedWalletId(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.related_wallet_id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'related_wallet_id' field has been set.
      * @return True if the 'related_wallet_id' field has been set, false otherwise.
      */
    public boolean hasRelatedWalletId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'related_wallet_id' field.
      * @return This builder.
      */
    public com.seanglay.events.TransactionCreatedEvent.Builder clearRelatedWalletId() {
      related_wallet_id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return created_at;
    }


    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public com.seanglay.events.TransactionCreatedEvent.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[6], value);
      this.created_at = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public com.seanglay.events.TransactionCreatedEvent.Builder clearCreatedAt() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransactionCreatedEvent build() {
      try {
        TransactionCreatedEvent record = new TransactionCreatedEvent();
        record.transaction_id = fieldSetFlags()[0] ? this.transaction_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.account_id = fieldSetFlags()[1] ? this.account_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.wallet_id = fieldSetFlags()[2] ? this.wallet_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.type = fieldSetFlags()[3] ? this.type : (com.seanglay.events.TransactionType) defaultValue(fields()[3]);
        record.amount = fieldSetFlags()[4] ? this.amount : (java.nio.ByteBuffer) defaultValue(fields()[4]);
        record.related_wallet_id = fieldSetFlags()[5] ? this.related_wallet_id : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.created_at = fieldSetFlags()[6] ? this.created_at : (java.time.Instant) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransactionCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransactionCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransactionCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<TransactionCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










