/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.seanglay.events;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class WalletCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4617846790518780022L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WalletCreatedEvent\",\"namespace\":\"com.seanglay.events\",\"fields\":[{\"name\":\"wallet_id\",\"type\":\"string\"},{\"name\":\"account_id\",\"type\":\"string\"},{\"name\":\"created_at\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<WalletCreatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WalletCreatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WalletCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WalletCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WalletCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WalletCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WalletCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WalletCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WalletCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence wallet_id;
  private java.lang.CharSequence account_id;
  private java.time.Instant created_at;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WalletCreatedEvent() {}

  /**
   * All-args constructor.
   * @param wallet_id The new value for wallet_id
   * @param account_id The new value for account_id
   * @param created_at The new value for created_at
   */
  public WalletCreatedEvent(java.lang.CharSequence wallet_id, java.lang.CharSequence account_id, java.time.Instant created_at) {
    this.wallet_id = wallet_id;
    this.account_id = account_id;
    this.created_at = created_at.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return wallet_id;
    case 1: return account_id;
    case 2: return created_at;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: wallet_id = (java.lang.CharSequence)value$; break;
    case 1: account_id = (java.lang.CharSequence)value$; break;
    case 2: created_at = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'wallet_id' field.
   * @return The value of the 'wallet_id' field.
   */
  public java.lang.CharSequence getWalletId() {
    return wallet_id;
  }


  /**
   * Sets the value of the 'wallet_id' field.
   * @param value the value to set.
   */
  public void setWalletId(java.lang.CharSequence value) {
    this.wallet_id = value;
  }

  /**
   * Gets the value of the 'account_id' field.
   * @return The value of the 'account_id' field.
   */
  public java.lang.CharSequence getAccountId() {
    return account_id;
  }


  /**
   * Sets the value of the 'account_id' field.
   * @param value the value to set.
   */
  public void setAccountId(java.lang.CharSequence value) {
    this.account_id = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public java.time.Instant getCreatedAt() {
    return created_at;
  }


  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.created_at = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new WalletCreatedEvent RecordBuilder.
   * @return A new WalletCreatedEvent RecordBuilder
   */
  public static com.seanglay.events.WalletCreatedEvent.Builder newBuilder() {
    return new com.seanglay.events.WalletCreatedEvent.Builder();
  }

  /**
   * Creates a new WalletCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WalletCreatedEvent RecordBuilder
   */
  public static com.seanglay.events.WalletCreatedEvent.Builder newBuilder(com.seanglay.events.WalletCreatedEvent.Builder other) {
    if (other == null) {
      return new com.seanglay.events.WalletCreatedEvent.Builder();
    } else {
      return new com.seanglay.events.WalletCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new WalletCreatedEvent RecordBuilder by copying an existing WalletCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new WalletCreatedEvent RecordBuilder
   */
  public static com.seanglay.events.WalletCreatedEvent.Builder newBuilder(com.seanglay.events.WalletCreatedEvent other) {
    if (other == null) {
      return new com.seanglay.events.WalletCreatedEvent.Builder();
    } else {
      return new com.seanglay.events.WalletCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for WalletCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WalletCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<WalletCreatedEvent> {

    private java.lang.CharSequence wallet_id;
    private java.lang.CharSequence account_id;
    private java.time.Instant created_at;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.seanglay.events.WalletCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.wallet_id)) {
        this.wallet_id = data().deepCopy(fields()[0].schema(), other.wallet_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.account_id)) {
        this.account_id = data().deepCopy(fields()[1].schema(), other.account_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.created_at)) {
        this.created_at = data().deepCopy(fields()[2].schema(), other.created_at);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing WalletCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.seanglay.events.WalletCreatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.wallet_id)) {
        this.wallet_id = data().deepCopy(fields()[0].schema(), other.wallet_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.account_id)) {
        this.account_id = data().deepCopy(fields()[1].schema(), other.account_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.created_at)) {
        this.created_at = data().deepCopy(fields()[2].schema(), other.created_at);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'wallet_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getWalletId() {
      return wallet_id;
    }


    /**
      * Sets the value of the 'wallet_id' field.
      * @param value The value of 'wallet_id'.
      * @return This builder.
      */
    public com.seanglay.events.WalletCreatedEvent.Builder setWalletId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.wallet_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'wallet_id' field has been set.
      * @return True if the 'wallet_id' field has been set, false otherwise.
      */
    public boolean hasWalletId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'wallet_id' field.
      * @return This builder.
      */
    public com.seanglay.events.WalletCreatedEvent.Builder clearWalletId() {
      wallet_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'account_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getAccountId() {
      return account_id;
    }


    /**
      * Sets the value of the 'account_id' field.
      * @param value The value of 'account_id'.
      * @return This builder.
      */
    public com.seanglay.events.WalletCreatedEvent.Builder setAccountId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.account_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'account_id' field has been set.
      * @return True if the 'account_id' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'account_id' field.
      * @return This builder.
      */
    public com.seanglay.events.WalletCreatedEvent.Builder clearAccountId() {
      account_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return created_at;
    }


    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public com.seanglay.events.WalletCreatedEvent.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[2], value);
      this.created_at = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public com.seanglay.events.WalletCreatedEvent.Builder clearCreatedAt() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WalletCreatedEvent build() {
      try {
        WalletCreatedEvent record = new WalletCreatedEvent();
        record.wallet_id = fieldSetFlags()[0] ? this.wallet_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.account_id = fieldSetFlags()[1] ? this.account_id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.created_at = fieldSetFlags()[2] ? this.created_at : (java.time.Instant) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WalletCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<WalletCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WalletCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<WalletCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










