apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: monitoring
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://postgres:Xk7mN9vpQL2nRw4j@postgres.database.svc.cluster.local:5432/postgres?sslmode=disable"
